/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on May 8, 2009, 1:47:11 PM
 */
package start;

import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import createTest.QuestionInputFrame;
import javax.swing.UnsupportedLookAndFeelException;
import takeTest.TestDetailsFrame;
import createTest.StartCreate;
import evaluateTest.FilesInputFrame;
import helper.Question;
import helper.Test;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jvnet.substance.skin.SubstanceSaharaLookAndFeel;

/**
 *
 * @author prasad
 */
public class MainFrame extends javax.swing.JFrame
{

    /** Creates new form MainFrame */
    public MainFrame()
    {
        initComponents();
        TakeTestButton.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CreateTestButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TakeTestButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        EvaluateTestButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EditTestButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyCampus Easy Test Maker");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("What do you want to do?");
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("<html>Create a test as a \"*.q\" Question file<br>and \"*.a\" answer file</html>");
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Do you wish to create<br>a new test file?</html>");
        jLabel2.setToolTipText("<html>Create a test as a \"*.q\" Question file<br>and \"*.a\" answer file</html>");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);

        CreateTestButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        CreateTestButton.setMnemonic('c');
        CreateTestButton.setText("Create Test");
        CreateTestButton.setToolTipText("<html>Create a test as a \"*.q\" Question file<br>and \"*.a\" answer file</html>");
        CreateTestButton.setName("CreateTestButton"); // NOI18N
        CreateTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTestButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateTestButton);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("Take a Test from \"*.q\" file");
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Do you wish to Attend<br>a test?</html>");
        jLabel3.setToolTipText("Take a Test from \"*.q\" file");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3);

        TakeTestButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        TakeTestButton.setMnemonic('t');
        TakeTestButton.setText("Take Test");
        TakeTestButton.setToolTipText("Take a Test from \"*.q\" file");
        TakeTestButton.setName("TakeTestButton"); // NOI18N
        TakeTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeTestButtonActionPerformed(evt);
            }
        });
        jPanel2.add(TakeTestButton);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("<html>Evaluate a test with \"*.a\" answer files<br>and \"*.rsp\" response files</html>");
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Do you wish to Evaluate<br>a test?</html>");
        jLabel4.setToolTipText("<html>Evaluate a test with \"*.a\" answer files<br>and \"*.rsp\" response files</html>");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel3.add(jLabel4);

        EvaluateTestButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        EvaluateTestButton.setMnemonic('e');
        EvaluateTestButton.setText("Evaluate Test");
        EvaluateTestButton.setToolTipText("<html>Evaluate a test with \"*.a\" answer files<br>and \"*.rsp\" response files</html>");
        EvaluateTestButton.setName("EvaluateTestButton"); // NOI18N
        EvaluateTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluateTestButtonActionPerformed(evt);
            }
        });
        jPanel3.add(EvaluateTestButton);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setToolTipText("<html>Create a test as a \"*.q\" Question file<br>and \"*.a\" answer file</html>");
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>Do you wish to Edit<br>an existing test file?</html>");
        jLabel5.setToolTipText("<html>Create a test as a \"*.q\" Question file<br>and \"*.a\" answer file</html>");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel4.add(jLabel5);

        EditTestButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        EditTestButton.setMnemonic('e');
        EditTestButton.setText("Edit Test");
        EditTestButton.setToolTipText("<html>Create a test as a \"*.q\" Question file<br>and \"*.a\" answer file</html>");
        EditTestButton.setName("EditTestButton"); // NOI18N
        EditTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTestButtonActionPerformed(evt);
            }
        });
        jPanel4.add(EditTestButton);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/cancel.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/gnome-unknown.png"))); // NOI18N
        jButton2.setText("Help");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, 0, 257, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2, jPanel3, jPanel4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateTestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CreateTestButtonActionPerformed
    {//GEN-HEADEREND:event_CreateTestButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser FC = new JFileChooser(Question.Dir);
        FC.setFileSelectionMode(FC.DIRECTORIES_ONLY);
        FC.setDialogTitle("Select Test Directory");
        if (FC.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File file = FC.getSelectedFile();
            if (file.isDirectory())
            {
                Question.Dir = file;
                JOptionPane.showMessageDialog(null,
                        "Please Move all the necessary media files to : \n" + file.getAbsolutePath(),
                        "Important!!!", JOptionPane.INFORMATION_MESSAGE);
                StartCreate ob = new StartCreate();
                ob.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Select Dir failed", "Error!!!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

}//GEN-LAST:event_CreateTestButtonActionPerformed

    private void TakeTestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TakeTestButtonActionPerformed
    {//GEN-HEADEREND:event_TakeTestButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.removeChoosableFileFilter(fc.getFileFilter());
        fc.setDialogTitle("Open a Question File");
        File testFile;
        fc.setFileFilter(new FileNameExtensionFilter("Question File", "q"));
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION)
        {
            testFile = fc.getSelectedFile();
            Question.setDir(testFile.getParentFile());
            if (testFile.exists())
            {
                try
                {
                    ObjectInputStream in =
                            new ObjectInputStream(new FileInputStream(testFile));
                    Test Questions = (Test) in.readObject();
                    File Ans = Questions.getRSP();

                    if (Ans.exists() == false)
                    {
                        Ans.mkdirs();
                    }
                    TestDetailsFrame t = new TestDetailsFrame(Questions);
                    t.setVisible(true);
                    this.dispose();
                } catch (IOException ex)
                {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex)
                {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, "File Does not Exist", "File Error!!!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

}//GEN-LAST:event_TakeTestButtonActionPerformed

    private void EvaluateTestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EvaluateTestButtonActionPerformed
    {//GEN-HEADEREND:event_EvaluateTestButtonActionPerformed
        // TODO add your handling code here:
        FilesInputFrame ob = new FilesInputFrame();
        ob.setVisible(true);
        this.dispose();
}//GEN-LAST:event_EvaluateTestButtonActionPerformed

    private void EditTestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EditTestButtonActionPerformed
    {//GEN-HEADEREND:event_EditTestButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();

        fc.removeChoosableFileFilter(fc.getFileFilter());
        fc.setFileFilter(new FileNameExtensionFilter("Question File", "q"));
        fc.setDialogTitle("Select Question file to Edit");
        if (fc.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
        {
            return;
        }

        File q = fc.getSelectedFile();
        JFileChooser fc2 = new JFileChooser();
        fc.removeChoosableFileFilter(fc.getFileFilter());
        fc2.setFileFilter(new FileNameExtensionFilter("Answer File", "a"));
        fc2.setDialogTitle("Select Answer file to Edit");
        if (fc2.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
        {
            return;
        }
        File a = fc2.getSelectedFile();


        Test Q, A;
        ObjectInputStream in;
        try
        {
            in = new ObjectInputStream(new FileInputStream(q));
            Q = (Test) in.readObject();
            in = new ObjectInputStream(new FileInputStream(a));
            A = (Test) in.readObject();
            if (Q.Name.equals(A.Name) && Q.Course.equals(A.Course) &&
                    Q.SubName.equals(A.SubName) && Q.SubCode.equals(
                    A.SubCode) && Q.DateOfTest.equals(A.DateOfTest) &&
                    Q.NoOfSections == A.NoOfSections)
            {
                Question.Dir = q.getParentFile();
                QuestionInputFrame QIF = new QuestionInputFrame();
                QIF.loadFile(Q, A);
                QIF.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Wrong file selected");
            }

        } catch (IOException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_EditTestButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,
                "EacyCampus EasyTestMaker was Created by:\n" +
                "Prasad TV\n" +
                "Poorna Prajna Thejasvi\n" +
                "Bharath V\n" +
                "YN Phaneendra Reddy\n\n" +
                "Please refer the Manual distributed \nwith EasyCampus package for Help.", "Help",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        UIManager.put("FileChooser.readOnly", Boolean.TRUE);
        try
        {
            UIManager.setLookAndFeel(new SubstanceSaharaLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateTestButton;
    private javax.swing.JButton EditTestButton;
    private javax.swing.JButton EvaluateTestButton;
    private javax.swing.JButton TakeTestButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    }
