/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SectionsInputFrame.java
 *
 * Created on May 8, 2009, 3:28:33 PM
 */
package createTest;

import helper.Section;
import helper.Test;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author prasad
 */
public class SectionsInputFrame extends javax.swing.JFrame
{

    private static final long serialVersionUID = -1304988300873575483L;
    Test TEST;
    GUISection SectionInputList[];
    QuestionInputFrame NEXT;
    StartCreate PARENT;

    /** Creates new form SectionsInputFrame */
    private SectionsInputFrame()
    {
        initComponents();
        SwingUtilities.updateComponentTreeUI(this);
    }

    public SectionsInputFrame(Test TEST,StartCreate Parent)
    {
        this();
        this.TEST = TEST;
        this.PARENT = Parent;

        int NoOfSections = TEST.NoOfSections;

        SectionInputList = new GUISection[NoOfSections];
        for (int i = 0; i < NoOfSections; i++)
        {
            SectionInputList[i] = new GUISection(i + 1);
            SectionsInputPanel.add(SectionInputList[i].SNo);
            SectionsInputPanel.add(SectionInputList[i].Name);
            SectionsInputPanel.add(SectionInputList[i].CutOff);
            SectionsInputPanel.add(SectionInputList[i].Time);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        SectionsInputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyCampus Easy Test Maker - Input Sections");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SectionsInputPanel.setName("SectionsInputPanel"); // NOI18N
        SectionsInputPanel.setLayout(new java.awt.GridLayout(0, 4, 5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Section No:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setName("jLabel1"); // NOI18N
        SectionsInputPanel.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Section Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setName("jLabel2"); // NOI18N
        SectionsInputPanel.add(jLabel2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cut Off");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setName("jLabel5"); // NOI18N
        SectionsInputPanel.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>Time<br>Duration</html>");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setName("jLabel6"); // NOI18N
        SectionsInputPanel.add(jLabel6);

        jPanel1.add(SectionsInputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        jScrollPane1.setViewportView(jPanel1);

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/next.png"))); // NOI18N
        Next.setMnemonic('n');
        Next.setText("Next");
        Next.setName("Next"); // NOI18N
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NextActionPerformed
    {//GEN-HEADEREND:event_NextActionPerformed
        // TODO add your handling code here:

        int NoOfSections = TEST.NoOfSections;

        String Name;
        double Cutoff;
        int Duration;

        for (int i = 0; i < NoOfSections; i++)
        {
            Name = SectionInputList[i].Name.getText();
            Cutoff = Double.parseDouble(SectionInputList[i].CutOff.getValue().
                    toString());
            Duration = Integer.parseInt(SectionInputList[i].Time.getValue().
                    toString());

            if (Name.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Name cannont be blank",
                        "Error in Section " + i + 1, JOptionPane.ERROR_MESSAGE);
                return;
            }

            TEST.SectionList[i] = new Section(Cutoff, Duration,
                    Name, i, Section.Question);
        }

//        Input each question for each Section

        NEXT = new QuestionInputFrame(TEST);
//        NEXT.loadData();
//        NEXT.loa
        NEXT.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_NextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PARENT.setVisible(true);
//        PARENT.dispose();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new SectionsInputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JPanel SectionsInputPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
