/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MediaDialog.java
 *
 * Created on May 17, 2009, 11:41:36 PM
 */
package takeTest;

import helper.Mp3Player;
import helper.Question;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author prasad
 */
public class MediaDialog extends javax.swing.JDialog
{
    Question QUESTION;
    ArrayList<String> IList;
    DefaultListModel IM, AM;
    ArrayList<String> AList;
    Mp3Player P;

    /** Creates new form MediaDialog */
    public MediaDialog(java.awt.Frame parent)
    {
        super(parent,false);
        initComponents();
    }

    public void setQUESTION(Question QUESTION)
    {
        ImagePanel.removeAll();
        this.QUESTION = QUESTION;
        IM = new DefaultListModel();
        IList = new ArrayList<String>(0);
        for(int i = 0;i < QUESTION.Images.length;i++)
        {
            IList.add(QUESTION.Images[i]);
            IM.addElement(QUESTION.Images[i]);
        }
        INameList.setModel(IM);
        if(IM.isEmpty() == false)
        {
            INameList.setSelectedIndex(0);
        }

        if(P != null)
        {
            P.finish();
        }

        AM = new DefaultListModel();
        AList = new ArrayList<String>(0);
        for(int i = 0;i < QUESTION.Audio.length;i++)
        {
            AList.add(QUESTION.Audio[i]);
            AM.addElement(QUESTION.Audio[i]);
        }
        ANameList.setModel(AM);
        if(AM.isEmpty() == false)
        {
            ANameList.setSelectedIndex(0);
        }

        if(PlayButton.getText().equals("Pause"))
        {
            PlayButton.setText("Play");
            ANameList.setEnabled(true);
        }

        if(AList.size() == 0)
        {
            PlayButton.setEnabled(false);
        }
        else
        {
            PlayButton.setEnabled(true);
        }
    }

    void finish()
    {
        if(P != null)
        {
            P.finish();

        }
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ImagePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        INameList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ANameList = new javax.swing.JList();
        PlayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Media Window");

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(12, 26));

        ImagePanel.setName("ImagePanel"); // NOI18N
        ImagePanel.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(ImagePanel);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        INameList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Images", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        INameList.setName("INameList"); // NOI18N
        INameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                INameListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(INameList);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/cancel.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        ANameList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Audio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        ANameList.setName("ANameList"); // NOI18N
        jScrollPane3.setViewportView(ANameList);

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/mplayer.png"))); // NOI18N
        PlayButton.setText("Play");
        PlayButton.setName("PlayButton"); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PlayButton))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PlayButton, jButton1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INameListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_INameListValueChanged
    {//GEN-HEADEREND:event_INameListValueChanged
        // TODO add your handling code here:
        int idx = INameList.getSelectedIndex();
        showImage(idx);
}//GEN-LAST:event_INameListValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(P != null)
        {
            P.finish();
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PlayButtonActionPerformed
    {//GEN-HEADEREND:event_PlayButtonActionPerformed
        // TODO add your handling code here:
        if(PlayButton.getText().equals("Play"))
        {
            PlayButton.setText("Pause");
            int idx = ANameList.getSelectedIndex();
            if(idx < 0)
            {
                return;
            }
            String name = AList.get(idx);
            File mp3 = new File(Question.Dir,name);
            if(mp3.exists())
            {
                P = new Mp3Player(mp3);
                P.start();
                ANameList.setEnabled(false);
            }

        }
        else if(PlayButton.getText().equals("Pause"))
        {
            PlayButton.setText("Play");
            P.finish();
            ANameList.setEnabled(true);
        }

}//GEN-LAST:event_PlayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                MediaDialog dialog = new MediaDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ANameList;
    private javax.swing.JList INameList;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void showImage(int X)
    {
        try
        {
            if(X < 0 || X >= IList.size())
            {
                return;
            }
            File Img = new File(Question.Dir,QUESTION.Images[X]);
            BufferedImage I = ImageIO.read(Img);
            ImageIcon ico = new ImageIcon(I);
            ImagePanel.removeAll();
            ImagePanel.add(new JLabel(ico));
            Dimension d = this.getSize();
            pack();
            this.setSize(d);
        }
        catch(IOException ex)
        {
            Logger.getLogger(MediaDialog.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
}
