/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestDetailsFrame.java
 *
 * Created on May 8, 2009, 12:28:31 AM
 */
package takeTest;

import helper.Test;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Bharath V
 */
public class TestDetailsFrame extends javax.swing.JFrame
{
    private static final long serialVersionUID = 2107008019586034830L;
    int CurrentSection = 0;
    Test QUESTIONS;
    SectionTestFrame[] Sections;

    /** Creates new form TestDetailsFrame */
    private TestDetailsFrame()
    {
        initComponents();
    }

    public TestDetailsFrame(Test Test)
    {
        this();
        QUESTIONS = Test;
        NameField.setText("Name : " + QUESTIONS.Name);
        CourseField.setText("Course : " + QUESTIONS.Course);
        SNameField.setText("Subject Name : " + QUESTIONS.SubName);
        SCodeField.setText("Subject Code : " + QUESTIONS.SubCode);
        SimpleDateFormat d = new SimpleDateFormat("dd-mm-yyyy");
        DateOfTestField.setText("Date of Test : " + d.format(QUESTIONS.DateOfTest));

//        QUESTIONS.setUSNStatus(true);
//        QUESTIONS.setClassStatus(true);
//        QUESTIONS.setSectionStatus(false);
////
//        QUESTIONS.USN = "19";
//        QUESTIONS.UserName = "Bharath";
//        QUESTIONS.Class = "8th";
//        QUESTIONS.Section = "a";
//        QUESTIONS.Instruction = "Turn Front";

        StudentDetailsPanel.add(new JLabel("Student Name"));
        StudentDetailsPanel.add(NameText);

        if(QUESTIONS.getUSNStatus() == true)
        {
            JLabel t = new JLabel("Student USN");
            t.setFont(new java.awt.Font("Dialog",0,12));
            StudentDetailsPanel.add(t);
            StudentDetailsPanel.add(USNText);

        }

        if(QUESTIONS.getClassStatus() == true)
        {
            JLabel t = new JLabel("Class");
            t.setFont(new java.awt.Font("Dialog",0,12));
            StudentDetailsPanel.add(t);
            StudentDetailsPanel.add(ClassText);

        }

        if(QUESTIONS.getSectionStatus() == true)
        {
            JLabel t = new JLabel("Section");
            t.setFont(new java.awt.Font("Dialog",0,12));
            StudentDetailsPanel.add(t);
            StudentDetailsPanel.add(SectionText);
        }

        JTextArea ta = new JTextArea(QUESTIONS.Instruction);
        ta.setEditable(false);
        ta.setFont(new java.awt.Font("Dialog",0,12));
        TestInstructionPanel.add(ta);

        Sections = new SectionTestFrame[QUESTIONS.NoOfSections];

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameText = new javax.swing.JTextField();
        USNText = new javax.swing.JTextField();
        ClassText = new javax.swing.JTextField();
        SectionText = new javax.swing.JTextField();
        TestDetailsPanel = new javax.swing.JPanel();
        NameField = new javax.swing.JLabel();
        CourseField = new javax.swing.JLabel();
        SNameField = new javax.swing.JLabel();
        SCodeField = new javax.swing.JLabel();
        DateOfTestField = new javax.swing.JLabel();
        StudentDetailsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TestInstructionPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        NameText.setFont(new java.awt.Font("Dialog", 1, 12));

        USNText.setFont(new java.awt.Font("Dialog", 1, 12));

        ClassText.setFont(new java.awt.Font("Dialog", 1, 12));

        SectionText.setFont(new java.awt.Font("Dialog", 1, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyCampus Easy Test Maker - Test Details");

        TestDetailsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        TestDetailsPanel.add(NameField);
        TestDetailsPanel.add(CourseField);
        TestDetailsPanel.add(SNameField);
        TestDetailsPanel.add(SCodeField);
        TestDetailsPanel.add(DateOfTestField);

        StudentDetailsPanel.setLayout(new java.awt.GridLayout(0, 2));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("STUDENT DETAILS");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TEST INSTRUCTION");

        TestInstructionPanel.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/next.png"))); // NOI18N
        jButton1.setMnemonic('o');
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/remove.png"))); // NOI18N
        jButton2.setMnemonic('c');
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TEST DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TestDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(StudentDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(TestInstructionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel8, jLabel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TestDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TestInstructionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jLabel10, jLabel9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Class = ClassText.getText();
        String Name = NameText.getText();
        String Section = SectionText.getText();
        String USN = USNText.getText();

        if(Name.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Name Field id Empty",
                    "Error!!!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(QUESTIONS.getUSNStatus() == true && USN.equals(""))
        {
            JOptionPane.showMessageDialog(this,"USN Field id Empty",
                    "Error!!!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(QUESTIONS.getClassStatus() == true && Class.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Class Field id Empty",
                    "Error!!!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(QUESTIONS.getSectionStatus() == true && Section.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Section Field id Empty",
                    "Error!!!",JOptionPane.ERROR_MESSAGE);
            return;
        }

        QUESTIONS.UserName = Name;
        QUESTIONS.USN = USN;
        QUESTIONS.Class = Class;
        QUESTIONS.Section = Section;
        SectionTestFrame ob = new SectionTestFrame(QUESTIONS);
        ob.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TestDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClassText;
    private javax.swing.JLabel CourseField;
    private javax.swing.JLabel DateOfTestField;
    private javax.swing.JLabel NameField;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel SCodeField;
    private javax.swing.JLabel SNameField;
    private javax.swing.JTextField SectionText;
    private javax.swing.JPanel StudentDetailsPanel;
    private javax.swing.JPanel TestDetailsPanel;
    private javax.swing.JPanel TestInstructionPanel;
    private javax.swing.JTextField USNText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}